# configuration for the chart-testing tool: https://github.com/helm/chart-testing
remote: origin
target-branch: main
lint-conf: .github/config/yamllint.yaml
chart-yaml-schema: .github/config/yamale.yaml
validate-maintainers: true
validate-chart-schema: true
validate-yaml: true
check-version-increment: true
chart-dirs:
  - charts
upgrade: true
skip-missing-values: true
release-label: release
chart-repos:
  - hajowieland=https://charts.wieland.tech
helm-extra-args: "--timeout 600s"
