# Explanation: Add the label 'ci-cd' to a PR if any file within the '.github' folder is changed
ci-cd:
- changed-files:
  - any-glob-to-any-file: '.github/config/*'
  - any-glob-to-any-file: '.github/workflows/*'

# charts
etcd-druid-certs:
- changed-files:
  - any-glob-to-any-file: charts/etcd-druid-certs/*
librechat-exporter:
  - changed-files:
      - any-glob-to-any-file: charts/librechat-exporter/*
librechat-rag-api:
- changed-files:
    - any-glob-to-any-file: charts/librechat-rag-api/*
miniflux:
- changed-files:
  - any-glob-to-any-file: charts/miniflux/*
test:
- changed-files:
  - any-glob-to-any-file: charts/test/*
web-check:
- changed-files:
    - any-glob-to-any-file: charts/web-check/*
