apiVersion: v2
name: librechat-exporter
description: A Prometheus metrics exporter for LibreChat
type: application
version: 1.0.0
appVersion: "2.0.0"
home: https://github.com/hajowieland/charts
keywords:
  - librechat
  - librechat-exporter
  - prometheus
  - exporter
  - metrics
  - ai
maintainers:
  - name: hajowieland
    email: mail@wieland.tech
sources:
  - https://github.com/virtUOS/librechat_exporter
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial commit of Chart
  artifacthub.io/links: |
    - name: support
      url: https://github.com/hajowieland/charts/issues
  artifacthub.io/signKey: |
    fingerprint: 9C4A952752AF51FD4E5FFBB4A23CFE514438886F
    url: https://charts.wieland.tech/public.key
