apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.etcdName }}-etcd-backup-restore-server
  labels:
    {{- include "etcd-druid-certs.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.etcdName }}-etcd-backup-restore-server-tls
  isCA: false
  usages:
    - "server auth"
    - "signing"
    - "key encipherment"
  dnsNames:
  - "{{ .Values.etcdName }}-local"
  - localhost
  - "127.0.0.1"
  privateKey:
    rotationPolicy: Always
    algorithm: {{ .Values.privateKey.algorithm }}
    size: {{ .Values.privateKey.size }}
  issuerRef:
    name: {{ .Values.etcdName }}-etcd-backup-restore-issuer
