apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.etcdName }}-etcd-server
  labels:
    {{- include "etcd-druid-certs.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.etcdName }}-etcd-server-tls
  isCA: false
  usages:
    - "server auth"
    - "signing"
    - "key encipherment"
  dnsNames:
  - "{{ .Values.etcdName }}-local"
  - "{{ .Values.etcdName }}-client"
  - "{{ .Values.etcdName }}-client.{{ .Release.Namespace }}"
  - "{{ .Values.etcdName }}-client.{{ .Release.Namespace }}.svc"
  - "{{ .Values.etcdName }}-client.{{ .Release.Namespace }}.svc.cluster.local"
  {{- $root := . -}}
  {{- range $i := until (int .Values.replicas) }}
  - "{{ $root.Values.etcdName }}-{{ $i }}.{{ $root.Values.etcdName }}-peer"
  - "{{ $root.Values.etcdName }}-{{ $i }}.{{ $root.Values.etcdName }}-peer.{{ $root.Release.Namespace }}"
  - "{{ $root.Values.etcdName }}-{{ $i }}.{{ $root.Values.etcdName }}-peer.{{ $root.Release.Namespace }}.svc"
  - "{{ $root.Values.etcdName }}-{{ $i }}.{{ $root.Values.etcdName }}-peer.{{ $root.Release.Namespace }}.svc.cluster.local"
  {{- end }}
  - localhost
  - "127.0.0.1"
  privateKey:
    rotationPolicy: Always
    algorithm: {{ .Values.privateKey.algorithm }}
    size: {{ .Values.privateKey.size }}
  issuerRef:
    name: {{ .Values.etcdName }}-etcd-issuer
