apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.etcdName }}-etcd-peer-issuer
  labels:
    {{- include "etcd-druid-certs.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ .Values.etcdName }}-etcd-peer-ca-tls
