name: Chart-Kubeconform

on:
  workflow_call:
  workflow_dispatch:

jobs:

  detect-changed-charts:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.get-changed-charts.outputs.matrix }}
    steps:
      - name: checkout git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ github.head_ref }}

      - name: setup helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Identify changed charts
        id: get-changed-charts
        run: |
          CHANGED_CHARTS=$(ct list-changed --config .github/config/chart-testing.yaml | jq -c --slurp --raw-input 'split("\n")[:-1] | map({chart: .})')
          echo "matrix=$CHANGED_CHARTS" >> $GITHUB_OUTPUT

      - name: Debug matrix ouput
        run: echo "${{ steps.get-changed-charts.outputs.matrix }}"

  kubeconform:
    needs: detect-changed-charts
    runs-on: ubuntu-24.04
    if: ${{ needs.detect-changed-charts.outputs.matrix != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.detect-changed-charts.outputs.matrix) }}
    steps:
      - name: checkout git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ github.head_ref }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: install pyyaml
        run: pip install pyyaml

      - name: setup helm
        uses: azure/setup-helm@v4

      - name: Set up kubeconform-helm plugin
        run: helm plugin install https://github.com/jtyr/kubeconform-helm

      - name: helm dependency update on changed chart
        run : helm dependency update ${{ matrix.chart }}

      - name: Run helm-kubeconform with optional CI values
        run: |
          CHART_PATH="${{ matrix.chart }}"
          VALUES_CI_FILE="$CHART_PATH/ci/values-ci.yaml"
          EXTRA_KUBECONFORM_ARGS=""

          echo "Checking for kubeconform CI values file: $VALUES_CI_FILE"
          if [[ -f "$VALUES_CI_FILE" ]]; then
            echo "CI values file '$VALUES_CI_FILE' found. Adding --values argument."
            EXTRA_KUBECONFORM_ARGS="--values \"$VALUES_CI_FILE\""
          else
            echo "CI values file '$VALUES_CI_FILE' not found. Proceeding without it."
          fi

          echo "Running helm kubeconform for chart '$CHART_PATH' with extra args: $EXTRA_KUBECONFORM_ARGS"
          bash -c "helm kubeconform --config .github/config/chart-kubeconform.yaml '$CHART_PATH' $EXTRA_KUBECONFORM_ARGS"
        shell: bash # Ensure bash is used for the [[ -f ]] conditional and command execution
